Repository EllairaT/Nutrii, pull requests merged in 2020-03, with the labels that each got.

#3 another commit
  src/nutrii/application/NutriiApplication.java
Labels: enhancement

#4 updated user classes + subclasses
  src/nutrii/application/ExtraActive.java
  src/nutrii/application/LightlyActive.java
  src/nutrii/application/ModeratelyActive.java
  src/nutrii/application/NutriiApplication.java
  src/nutrii/application/Sedentary.java
  src/nutrii/application/User.java
  src/nutrii/application/VeryActive.java
Labels: enhancement

#5 added compounds
  .gitignore
  nbproject/project.properties
  src/nutrii/application/Compounds.java
  src/nutrii/application/FoodItem.java
  src/nutrii/application/ItemActions.java
  src/nutrii/application/Minerals.java
  src/nutrii/application/ModeratelyActive.java
  src/nutrii/application/NutriiApplication.java
  src/nutrii/application/Sedentary.java
  src/nutrii/application/User.java
  src/nutrii/application/Vitamins.java
Labels: enhancement

#6 removed unused import
  src/nutrii/application/NutriiApplication.java
  src/nutrii/application/Vitamins.java
Labels: rewrote/removed things

#7 added more methods to NutriiApplication
  src/nutrii/application/NutriiApplication.java
Labels: help wanted, invalid

#10 added comments, TODO's, and methods.
  src/nutrii/application/Compounds.java
  src/nutrii/application/Food.java
  src/nutrii/application/FoodItem.java
  src/nutrii/application/FoodItemDatabase.java
  src/nutrii/application/NutriiApplication.java
  src/nutrii/application/NutritionTracker.java
  src/nutrii/application/Recommender.java
  src/nutrii/application/Report.java
  src/nutrii/application/Supplement.java
  src/nutrii/application/User.java
Labels: documentation, help wanted, rewrote/removed things

#13 pls accept
  src/nutrii/application/LightlyActive.java
Labels: enhancement
